openapi: 3.0.1
info:
  title: Library Swagger Api
  contact:
    name: Ekaterina Gorshunova
    email: ekaterina.gorshunova@intexsoft.by
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /books:
    $ref: './resources/books.yaml'
  /authors:
    $ref: './resources/authors.yaml'
  /books/{id}:
    $ref: './resources/booksid.yaml'
  /authors/{id}:
    $ref: './resources/authorsid.yaml'
  /books/deleteAll:
    $ref: './resources/booksdeleteAll.yaml'
  /books/delete/{id}:
    $ref: './resources/booksdeleteid.yaml'
  /authors/deleteAll:
    $ref: './resources/authorsdeleteAll.yaml'
  /authors/delete/{id}:
    $ref: './resources/authorsdeleteid.yaml'
  /users:
    $ref: './resources/users.yaml'
  /users/{id}:
    $ref: './resources/usersid.yaml'
  /users/deleteAll:
    $ref: './resources/usersdeleteAll.yaml'
  /users/delete/{id}:
    $ref: './resources/usersdeleteid.yaml'
  /feedback:
    $ref: './resources/feedback.yaml'
  /feedback/{id}:
    $ref: './resources/feedbackid.yaml'
  /feedback/deleteAll:
    $ref: './resources/feedbackdeleteAll.yaml'
  /feedback/delete/{id}:
    $ref: './resources/feedbackdeleteid.yaml'
  /bookhistory:
    $ref: './resources/bookhistory.yaml'
  /bookhistory/{id}:
    $ref: './resources/bookhistoryid.yaml'
  /bookhistory/deleteAll:
    $ref: './resources/bookhistorydeleteAll.yaml'
  /bookhistory/delete/{id}:
    $ref: './resources/bookhistorydeleteid.yaml'
  /top10books:
    $ref: './resources/top10books.yaml'
  /top10authors:
    $ref: './resources/top10authors.yaml'
components:
  schemas:
    AuthorDTO:
      $ref: './schemas/AuthorDTO.yaml'
    BookDTO:
      $ref: './schemas/BookDTO.yaml'
    UserDTO:
      $ref: './schemas/UserDTO.yaml'
    FeedbackDTO:
      $ref: './schemas/FeedbackDTO.yaml'
    BookHistoryDTO:
      $ref: './schemas/BookHistoryDTO.yaml'
